name: Python Compilation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10 # Ви можете вказати версію Python, яку ви хочете використовувати

    #- name: Install dependencies
    #  run: pip install -r requirements.txt  # Якщо у вас є файли вимог, ви можете їх встановити тут

    - name: Compile Python code
      run: python -m py_compile tiktaktoe.py  # Замініть `your_script.py` на ім'я вашого Python-файлу

    - name: Commit compiled files
      run: |
        git config user.name "Dmytr9o"
        git config user.email "d.dmytryshyn.o@gmail.com"
        git add __pycache__  # Додаємо файли, які були компільовані
        git commit -m "Add compiled Python files"
        git push
