#test
name: Python Build and Deploy

on:
  push:
    branches:
      - dev  # Змініть гілку, яку ви хочете використовувати

jobs:
    build:
      runs-on: ubuntu-latest  # Ви можете вибрати інший образ, який підходить вам

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0  # Виберіть версію Python, яку ви хочете використовувати

    - name: Compile Python File
      run: |
        pip install pyinstaller
        pyinstaller --onefile --distpath /compiled tiktactoe.py
 

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: python-build
        path: /compiled/build/tiktactoe # Вкажіть шлях до вашого скомпільованого файлу Python

     - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_SECRET }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: future_branche
          delete-branch: true
          title: 'Update report'
          body: |
            Update report
          labels: |
            report
            automated pr
          assignees: Dmytr9o
          draft: false
