#test
name: Python Build and Deploy

on:
  push:
    branches:
      - dev  # Змініть гілку, яку ви хочете використовувати

jobs:
  build:
    runs-on: ubuntu-latest  # Ви можете вибрати інший образ, який підходить вам

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0  # Виберіть версію Python, яку ви хочете використовувати

    - name: Program runs?
      run: |
          python -m py_compile tiktactoe.py

    - name: Compile Python File
      run: |
          pip install pyinstaller
          pyinstaller --onefile tiktactoe.py
 

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: python-build
        path: build/tiktactoe # Вкажіть шлях до вашого скомпільованого файлу Python

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
          token: ${{ secrets.GH_SECRET }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: feature-branch
          delete-branch: true
          title: 'Update report'
          body: |
            Додавання нової функціональності
          labels: |
            report
            automated pr
          assignees: Dmitr9o
          reviewers: Dmitr9o
          draft: false