name: Python Compilation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0 # Ви можете вказати версію Python, яку ви хочете використовувати

    #- name: Install dependencies
    #  run: pip install -r requirements.txt  # Якщо у вас є файли вимог, ви можете їх встановити тут
    - name: Show current directory
      run: pwd

    - name: Show ls(DEBUG 1)
      run: ls

    - name: Set working directory
      run: cd $GITHUB_WORKSPACE

    - name: Show ls(DEBUG 2)
      run: ls
    - name: Show current directory(DEBUG 2)
      run: pwd
  
    - name: Compile Python code
      run: python -m py_compile tiktactoe.py

    - name: Commit compiled Python files
      run: |
        git config user.name "Dmytr9o"
        git config user.email "youremail@example.com"
        git add __pycache__  # Додаємо файли, які були компільовані
        git commit -m "Add compiled Python files"
        git push --set-upstream origin $GITHUB_REF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

